version: 2
updates:
  ######
  # main
  - package-ecosystem: maven
    target-branch: "main"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    ignore:
    - dependency-name: ch.qos.logback:logback-classic
      versions:
      - ">= 1.3.0"
    - dependency-name: javax.inject:javax.inject
      versions:
      - ">= 0"
    - dependency-name: net.sf.saxon:Saxon-HE
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven:maven-core
      versions:
      - ">= 0"
    - dependency-name: org.slf4j:slf4j-api
      versions:
      - ">= 0"
    # https://webtide.com/jetty-10-and-11-have-arrived/ (javax support still needed for JGit GitServlet)
    - dependency-name: org.eclipse.jetty:jetty-server
      versions:
      - ">= 11.0.0"
    - dependency-name: org.eclipse.jetty:jetty-servlet
      versions:
      - ">= 11.0.0"
    # plexus-xml seems to be aimed for Maven 4
    - dependency-name: org.codehaus.plexus:plexus-xml
      versions:
      - ">= 4.0.0"
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "weekly"
  #####
  # 3.x
  - package-ecosystem: maven
    target-branch: "3.x"
    commit-message:
      prefix: "[3.x] "
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: org.eclipse.jgit:org.eclipse.jgit
      versions:
      - ">= 6.0.0.202111291000-r"
    - dependency-name: org.eclipse.jgit:org.eclipse.jgit.ssh.jsch
      versions:
      - ">= 6.0.0.202111291000-r"
    - dependency-name: org.eclipse.jgit:org.eclipse.jgit.http.server
      versions:
      - ">= 6.0.0.202111291000-r"
    - dependency-name: org.eclipse.jgit:org.eclipse.jgit.junit.ssh
      versions:
      - ">= 6.0.0.202111291000-r"
    - dependency-name: ch.qos.logback:logback-classic
      versions:
      - ">= 1.3.0"
    - dependency-name: javax.inject:javax.inject
      versions:
      - ">= 0"
    - dependency-name: net.sf.saxon:Saxon-HE
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven:maven-core
      versions:
      - ">= 0"
    - dependency-name: org.slf4j:slf4j-api
      versions:
      - ">= 0"
    # https://webtide.com/jetty-10-and-11-have-arrived/ (Java 8 support still needed)
    - dependency-name: org.eclipse.jetty:jetty-server
      versions:
      - ">= 10.0.0"
    - dependency-name: org.eclipse.jetty:jetty-servlet
      versions:
      - ">= 10.0.0"
    # Mockito 5 dropped Java 8 support
    - dependency-name: org.mockito:mockito-core
      versions:
      - ">= 5.0.0"
    - dependency-name: org.mockito:mockito-junit-jupiter
      versions:
      - ">= 5.0.0"
    # the following plugins have abandoned Maven < 3.6.3
    - dependency-name: org.apache.maven.plugins:maven-dependency-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-clean-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-deploy-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-enforcer-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-failsafe-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-gpg-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-help-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-jar-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-install-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-javadoc-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-plugin-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugin-tools:maven-plugin-annotations
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-release-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-site-plugin
      versions:
      - ">= 0"
    - dependency-name: org.apache.maven.plugins:maven-surefire-plugin
      versions:
      - ">= 0"
    - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
      versions:
      - ">= 0"
    - dependency-name: com.github.spotbugs:spotbugs-annotations
      versions:
      - ">= 0"
  - package-ecosystem: "github-actions"
    target-branch: "3.x"
    commit-message:
      prefix: "[3.x] "
    directory: "/"
    schedule:
      interval: "weekly"
